# Site settings
title: Sailboat Project Log
description: "This is my project log for projects on my Allied Seabreeze."
permalink: :categories/:year-:month-:day-:title:output_ext
dropbox_root: "https://www.dropbox.com/sh/r7c0wsx9tmq5wnk/AACswH-WPDpc9bvx6o14_i2pa"

sass:
  sass_dir: css
  style: compressed

# Build settings
markdown: kramdown

exclude:
- README.md
- Makefile
- LICENSE
- CNAME
- rawpix

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "projects"
    values:
      layout: "project"
  -
    scope:
      path: "projects/toerails"
    values:
      key: "toerails"
      project: "Teak Toe Rail Replacement"
      top: "2018-11-18-overview.html"
      dbpath: "https://www.dropbox.com/sh/qpv5q61h6hakcbo/AADFqm03_3fMbY-twd9Nyd6Ha"
  -
    scope:
      path: "projects/chainplates"
    values:
      key: "chainplates"
      project: "Rebed Chain Plates With Butyl Tape"
      top: "2020-07-24-chainplates.html"
      dbpath: "https://www.dropbox.com/sh/tplimnh9zd8jyxr/AAB29UJpKhwkClyCXo4jrmBRa"
  -
    scope:
      path: "projects/coamings"
    values:
      key: "coamings"
      project: "Refurbish Mahogany Cockpit Coamings"
      top: "2021-01-01-coamings.html"
      dbpath: "https://www.dropbox.com/sh/vog24ola3asvokh/AACGSpm9i6TJU7GXxBQ-sI46a"
  -
    scope:
      path: "projects/hull"
    values:
      key: "hull"
      project: "Refurbish and Repaint Hull with Alexseal"
      top: "2020-07-01-overview.html"
      dbpath: "https://www.dropbox.com/sh/ayixnoloexg9f2q/AADPELyvRKagSJoLniqv6ywAa"
