# Site settings
title: Potomac Boatcraft
description: "This is my project log for projects on my Allied Seabreeze."
permalink: :categories/:year-:month-:day-:title:output_ext
dropbox_root: "https://www.dropbox.com/sh/r7c0wsx9tmq5wnk/AACswH-WPDpc9bvx6o14_i2pa"

sass:
  sass_dir: css
  style: compressed

# Build settings
markdown: kramdown

exclude:
- README.md
- Makefile
- bogus
- LICENSE
- CNAME
- rawpix

menu:
- ["Home", "/"]
- ["Gallery", "/gallery.html"]
- ["Projects", "/projects.html"]
- ["Contact", "/contact.html"]

contact:
  email: mailto:potomacboatcraft@gmail.com
  fbook: https://facebook.com/potomacboatcraft
  insta: https://instagram.com/potomacboatcraft
  sailbuddy: https://apps.apple.com/us/app/sail-buddy/id1100095207

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "recent"
    values:
      layout: "project"
      awspath: "https://zognet-boatworks.s3.amazonaws.com/recent-projects"
  -
    scope:
      path: "projects"
    values:
      layout: "project"
  -
    scope:
      path: "projects/toerails"
    values:
      key: "toerails"
      project: "Teak Toe Rail Replacement"
      top: "2018-11-18-overview.html"
      awspath: "https://zognet-boatworks.s3.amazonaws.com/toerails"
      draft: false
  -
    scope:
      path: "projects/coamings"
    values:
      key: "coamings"
      project: "Refurbish Mahogany Cockpit Coamings"
      top: "2021-01-01-coamings.html"
      awspath: "https://zognet-boatworks.s3.amazonaws.com/coamings"
  -
    scope:
      path: "projects/hull"
    values:
      key: "hull"
      project: "Refurbish and Repaint Hull with Alexseal"
      top: "2020-07-01-overview.html"
      awspath: "https://zognet-boatworks.s3.amazonaws.com/hull"
  -
    scope:
      path: "projects/hatch-cover"
    values:
      key: "hatch-cover"
      project: "Replacement Fiberglass Hatch Cover"
      top: "2021-01-01-overview.html"
      awspath: "https://zognet-boatworks.s3.amazonaws.com/hatch-cover"
